apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-servicemonitor
  namespace: myapp-ns
spec:
  selector:
    matchLabels:
      app: myapp
  endpoints:
    - port: 8080
      interval: 30s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-logging-config
  namespace: myapp-ns
data:
  loki.yaml: |
    pipeline_stages:
      - json
      - labels:
          app: myapp
